<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Test|AnyCPU' ">
    <IntermediateOutputPath>obj\Release\netstandard2.0</IntermediateOutputPath>
    <DebugType></DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;RELEASE;NETSTANDARD;NETSTANDARD2_0</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1534" />
    <PackageReference Include="Microsoft.Azure.Mobile.Client" Version="4.0.2" />
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle" Version="3.0.0.5" />
    <PackageReference Include="Syncfusion.Xamarin.SfListView" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Xamarin.Buttons" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Xamarin.SfPicker" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Xamarin.SfMaskedEdit" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Xamarin.Core" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Xamarin.SfNumericUpDown" Version="18.1.0.42" />
    <PackageReference Include="Microsoft.Azure.Mobile.Client.SQLiteStore" Version="4.0.2" />
    <PackageReference Include="Syncfusion.Xamarin.SfBusyIndicator" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Xamarin.SfTabView" Version="18.1.0.42" />
    <PackageReference Include="Microsoft.Identity.Client" Version="2.7.0" />
    <PackageReference Include="Microsoft.AppCenter" Version="1.13.0" />
    <PackageReference Include="Microsoft.AppCenter.Push" Version="1.13.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.5.231" />
    <PackageReference Include="Syncfusion.Xamarin.SfPullToRefresh" Version="18.1.0.42" />
    <PackageReference Include="RestSharp" Version="106.6.10" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="1.13.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="1.13.0" />
    <PackageReference Include="Syncfusion.Xamarin.SfComboBox" Version="18.1.0.42" />
    <PackageReference Include="NodaTime" Version="2.4.6" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
    <PackageReference Include="Syncfusion.Xamarin.SfCalendar" Version="18.1.0.42" />
    <PackageReference Include="ZXing.Net.Mobile" Version="2.4.1" />
    <PackageReference Include="ZXing.Net.Mobile.Forms" Version="2.4.1" />
    <PackageReference Include="Plugin.Permissions" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\" />
    <Folder Include="Views\Football\" />
    <Folder Include="Model\" />
    <Folder Include="Converters\" />
    <Folder Include="Data\" />
    <Folder Include="Constants\" />
    <Folder Include="Controller\" />
    <Folder Include="Views\Admin\" />
    <Folder Include="ViewModel\" />
    <Folder Include="Extensions\" />
    <Folder Include="Services\" />
    <Folder Include="Views\MatchConfigurations\" />
    <Folder Include="Views\MyTeam\" />
    <Folder Include="Styles\" />
    <Folder Include="Templates\" />
    <Folder Include="Views\Cricket\" />
    <Folder Include="ViewModel\Cricket\" />
    <Folder Include="Views\Tickets\" />
    <Folder Include="ViewModel\Football\" />
    <Folder Include="Views\Setting\" />
    <Folder Include="ViewModel\Shop\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Views\Football\MatchStatsPopUpPage %28another copy%29.cs" />
    <Compile Remove="Model\TwitterViewModel.cs" />
    <Compile Remove="Templates\HeadToHeadList %28copy%29.xaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Views\Football\NewsPage.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>NewsPage.xaml</DependentUpon>
    </Compile>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Views\MatchConfigurations\FixtureListPage.xaml.cs">
      <DependentUpon>FixtureListPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MatchConfigurations\FixturePage.xaml.cs">
      <DependentUpon>FixturePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Templates\FixtureList.xaml.cs">
      <DependentUpon>FixtureList.xaml</DependentUpon>
    </Compile>
    <Compile Update="Templates\FixtureListHeader.xaml.cs">
      <DependentUpon>FixtureListHeader.xaml</DependentUpon>
    </Compile>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Views\FootballMasterDetailPageMaster.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Views\Cricket\TeamProfilePage.xaml.cs">
      <DependentUpon>TeamProfilePage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>